# $OpenBSD: Makefile,v 1.10 2021/12/17 14:55:45 patrick Exp $

LIB=	LLVMWindowsDriver
NOPROFILE=

CPPFLAGS+=	-I${LLVM_SRCS}/include/llvm/WindowsDriver

SRCS+=	MSVCPaths.cpp

.PATH:	${.CURDIR}/../../../llvm/llvm/lib/WindowsDriver
